### ISSUE TITLE
PlaceholderAPI support

### ISSUE THREAD

**Issue by devangerpl** [sasi2006166/Fallback-Server#12]
Hi. Will you add PlaceholderAPI support from which you can download information on what lobby, for example, it is located on? Additionally, some developed plugin documentation.

**Comment by PystoyPlayer** [comment]
> Hi. Will you add PlaceholderAPI support from which you can download information on what lobby, for example, it is located on? Additionally, some developed plugin documentation.

why ? I won't claim (English isn't even my native language), but `https://www.spigotmc.org/threads/placeholder-api-servername-placeholder.242394` doesn't work ?

**Comment by sasi2006166** [comment]
Hi, I'll soon provide a developer API, also, PAPI is spigot side, how am I supposed to integrate it in bungeecord / velocity?

**Comment by devangerpl** [comment]
@PystoyPlayer 
> > Hi. Will you add PlaceholderAPI support from which you can download information on what lobby, for example, it is located on? Additionally, some developed plugin documentation.
> 
> why ? I won't claim (English isn't even my native language), but `https://www.spigotmc.org/threads/placeholder-api-servername-placeholder.242394` doesn't work ?


English is also not my native language and it is even difficult for me to write in English so I use google translator: D.

Regarding what you are showing, it just bugs you the name of the server.

My point is that Lobby # 1 or Channel # 1 should be written, and when I have more of these servers, I add # 2 # 3 # 4. How could you rewrite it and do what you type on such a basis.


![obraz_2022-07-10_064823531](https://user-images.githubusercontent.com/41342020/178131720-d701d2aa-f816-43bf-b3f6-9f45c66de16b.png)


@sasi2006166 
> Hi, I'll soon provide a developer API, also, PAPI is spigot side, how am I supposed to integrate it in bungeecord / velocity?


You just do so that you can download the information and apply my method above.
then when you integrate it, you can, for example, something like% fallback_server_player% and it will tell us on what server it is by name.
