### ISSUE TITLE
Suggestions for updates

### ISSUE THREAD

**Issue by Coquettishpig** [sasi2006166/Fallback-Server#13]
This plugin is great, but I don't think it's a perfect replacement for other hub plugins，I wish I could add something like BungeeHub's Server group，Grouping for server selection lobby servers

**Comment by sasi2006166** [comment]
Hi, yeah that's already on my feature list.

**Comment by Coquettishpig** [comment]
> 嗨，是的，这已经在我的功能列表中了。

I'm sorry, I didn't see him.

**Comment by Coquettishpig** [comment]
I think it may not be as perfect as BungeeHub, will you improve this feature next?
BungeeHub Example:
Group:
  Lobby:
    name: "&aLobby"
    type: SERVER
  Bedwarslobby:
    name: "&aBedwarslobby"
    type: SERVER
    server:
    - Bedwars
    - BedwarsRushMode
    queue: Bedwarslobby
