### ISSUE TITLE
Fallback mode

### ISSUE THREAD

**Issue by Sloth-on-meth** [sasi2006166/Fallback-Server#15]
fallback mode seems to not work. i put it in the config but i never get reconnected automatically. the plugin didnt generate that option in the default config eitehr

**Comment by sasi2006166** [comment]
Welcome to issue repository, may you talk with me on Telegram? (@CandiesJar) or discord? If you prefer discord comment your tag, thank you.

**Comment by Sloth-on-meth** [comment]
Heyo, the discord Invite link in the config doesn't work anymore. I will
contact you later :)

**Comment by sasi2006166** [comment]
This is the new link: https://discord.gg/dJ8DG2cSzt
