### ISSUE TITLE
Bug in velocity version FallbackServer

### ISSUE THREAD

**Issue by ghost** [sasi2006166/Fallback-Server#16]
With the Velocity version of FallbackServer, when only / is sent, it behaves the same as /lobby or /hub.
Therefore, another plug-in cannot be used. So please fix it.

**Comment by ghost** [comment]
![image](https://github.com/sasi2006166/Fallback-Server/assets/108934000/518c5d76-a96f-45e3-b170-d07c68d9802f)
![image](https://github.com/sasi2006166/Fallback-Server/assets/108934000/402c49a9-ca66-4cc7-8ecc-fa9bf8e8d269)

**Comment by frafol** [comment]
Try the new beta releases found on the Discord

**Comment by ghost** [comment]
ok

**Comment by sasi2006166** [comment]
Your issue has been fixed in 3.2.0-Beta1 available on my discord server.
