### ISSUE TITLE
"fallback_list" not being respected

### ISSUE THREAD

**Issue by austv** [sasi2006166/Fallback-Server#33]
I have two lobbys. In Fallback_list I add only one of them and restarted the proxy. However, this list is not being respected. This is my config:

![image](https://github.com/sasi2006166/Fallback-Server/assets/66658478/2e6c1dde-213f-414b-8e7c-458b0314aa95)

Then, when I restarted a server to fallback to the lobby, I get joined in another lobby, my main lobby.
![image](https://github.com/sasi2006166/Fallback-Server/assets/66658478/042d54d2-76c4-4a94-a97f-8349d6285d4e)

This "lobby-2" still works. When I'm on "lobby" and the server is stopped, I got moved to "lobby-2".
![image](https://github.com/sasi2006166/Fallback-Server/assets/66658478/e8c981b6-2ae7-4fde-87f1-9ccf3edf018c)

**Info:**
Using _Velocity 3.3.0-SNAPSHOT (git-825c3c68-b348)_ and FS 3.2.0-Beta2

**Comment by sasi2006166** [comment]
Hello, join the discord please, I need more informations. https://discord.gg/dJ8DG2cSzt
