### ISSUE TITLE
Delivery problem

### ISSUE THREAD

**Issue by 157946a** [sasi2006166/Fallback-Server#5]
This problem arises like this. For example, if I set the return to lobby, and then I input the wrong login password, or the login server is temporarily closed, I will skip the password correct stage and enter the lobby directly. It is the same as without a password. This problem is Also appeared in bungeekick, hope to fix it urgently

**Comment by frafol** [comment]
> This problem arises like this. For example, if I set the return to lobby, and then I input the wrong login password, or the login server is temporarily closed, I will skip the password correct stage and enter the lobby directly. It is the same as without a password. This problem is Also appeared in bungeekick, hope to fix it urgently

Please set up correctly AuthMeBungee and set 
`allServersAreAuthServers: false` 

This way FallbackServer will not be able to send you to the Lobby before login.

**Comment by sasi2006166** [comment]
Issue closed, no more comments, re-open if necessary.
