### ISSUE TITLE
Joining and leaving the hub after leaving the network

### ISSUE THREAD

**Issue by florensm** [sasi2006166/Fallback-Server#7]
Hi i like this plugin so much, but one thing that bothers me is that it spams a join and leave message in the server that i have set in the config. 

![image](https://user-images.githubusercontent.com/52450422/147881335-ce1edec5-b57d-4755-a385-e4fee8613d9e.png)

I know that its because of this plugin because when i disable it, it doesnt do this anymore.

**Comment by sasi2006166** [comment]
Hello, sorry for late responde, little busy since i got coronavirus, can you contact me on discord? i need some more informations.
